language: perl
perl:
  - "5.30"
  - "5.24"
  - "5.20"
  - "5.16"
env:
  - "HARNESS_OPTIONS=j9"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage IO::Socket::SSL"
  - "cpanm -n --installdeps ."
notifications:
  email: false
